[workspace]
resolver = "2"
members = [
    "testangel",
    "testangel-arithmetic",
    "testangel-compare",
    "testangel-convert",
    "testangel-evidence",
    "testangel-ipc",
    "testangel-regex",
    "testangel-user-interaction",
]
