[workspace.package]
version = "0.20.6"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "testangel",
    "testangel-arithmetic",
    "testangel-compare",
    "testangel-convert",
    "testangel-date",
    "testangel-engine",
    "testangel-engine-macros",
    "testangel-evidence",
    "testangel-ipc",
    "testangel-rand",
    "testangel-regex",
    "testangel-user-interaction",
]
