[workspace.package]
version = "0.20.8"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "testangel",
    "testangel-engine",
    "testangel-engine-macros",
    "testangel-evidence",
    "testangel-ipc",
    "testangel-user-interaction",
]
