[workspace]
members = [
    "testangel",
    "testangel-arithmetic",
    "testangel-compare",
    "testangel-convert",
    "testangel-evidence",
    "testangel-ipc",
    "testangel-regex",
]
