# Relm4 icons config has to lie outside the "testangel" folder due to it not being workspace-compatible (for now)
app_id = "uk.hpkns.testangel"
base_resource_path = "/uk/hpkns/testangel/"

icons = [ "play", "menu", "lightbulb", "papyrus-vertical", "puzzle-piece", "edit", "plus", "x-circular", "up", "down", "tag", "gear" ]
icon_folder = "testangel/icons"
