[package]
name = "testangel-engine-macros"
authors = ["Lily Hopkins <lily@hpkns.uk>"]
description = "Macros for testangel-engine."
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true
