[package]
name = "testangel-engine-macros"
authors = ["Lily Hopkins <lily@hpkns.uk>"]
description = "Macros for testangel-engine."
version = "0.17.1"
edition = "2021"

[lib]
proc-macro = true
