name: Build Rust Applications

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Install dependencies
        run: |
          sudo apt -y update && sudo apt -y install libatk1.0-dev libgtk-3-dev

      - name: Build
        run: |
          # Build
          cargo build -p testangel --bin testangel --release
          cargo build -p testangel --bin testangel-executor --no-default-features --features cli --release
          cargo build -p testangel-arithmetic --release
          cargo build -p testangel-compare --release
          cargo build -p testangel-convert --release
          cargo build -p testangel-evidence --release
          # Prepare output dir
          mkdir -p build || exit 1
          cp target/release/testangel build/
          cp target/release/testangel-executor build/
          # Prepare engines
          mkdir -p build/engines || exit 1
          cp target/release/libtestangel_arithmetic.so build/engines
          cp target/release/libtestangel_compare.so build/engines
          cp target/release/libtestangel_convert.so build/engines
          cp target/release/libtestangel_evidence.so build/engines

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: tar
          path: build
          filename: release-linux-amd64.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release-linux-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: |
          cargo build -p testangel --bin testangel --release
          cargo build -p testangel --bin testangel-executor --no-default-features --features cli --release
          cargo build -p testangel-arithmetic --release
          cargo build -p testangel-compare --release
          cargo build -p testangel-convert --release
          cargo build -p testangel-evidence --release
          mkdir build
          copy target/release/testangel.exe build/
          cargo build -p testangel --bin testangel --release --features windows-keep-console-window
          copy target/release/testangel.exe build/testangel-dbg.exe
          copy target/release/testangel-executor.exe build/
          mkdir build/engines
          copy target/release/testangel_arithmetic.dll build/engines/
          copy target/release/testangel_compare.dll build/engines/
          copy target/release/testangel_convert.dll build/engines/
          copy target/release/testangel_evidence.dll build/engines/

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          path: build
          filename: release-win.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: |
          # Build
          cargo build -p testangel --bin testangel --release
          cargo build -p testangel --bin testangel-executor --no-default-features --features cli --release
          cargo build -p testangel-arithmetic --release
          cargo build -p testangel-compare --release
          cargo build -p testangel-convert --release
          cargo build -p testangel-evidence --release
          # Prepare output dir
          mkdir -p build || exit 1
          cp target/release/testangel build/
          cp target/release/testangel-executor build/
          # Prepare engines
          mkdir -p build/engines || exit 1
          cp target/release/libtestangel_arithmetic.dylib build/engines
          cp target/release/libtestangel_compare.dylib build/engines
          cp target/release/libtestangel_convert.dylib build/engines
          cp target/release/libtestangel_evidence.dylib build/engines

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: tar
          path: build
          filename: release-darwin.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release-darwin.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
